### ISSUE TITLE
Buttons don't look right on macOS

### ISSUE THREAD

**Issue by jackwilsdon** [cookiej91/challenge-generator#20]
**Describe the bug**
Buttons don't look right on macOS (there is a rounded border on them)

**To Reproduce**
1. Use macOS
2. Visit the challenge generator

**Expected behavior**
The buttons look right

**Screenshots**
<img width="358" alt="Screen Shot 2019-05-27 at 14 25 23" src="https://user-images.githubusercontent.com/1843197/58422801-6ed87600-808b-11e9-800c-1a048b9b5cd8.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Google Chrome
 - Version: 74.0.3729.169

**Comment by josh-cook** [comment]
Fixed by #21
