### ISSUE TITLE
Add a background 

### ISSUE THREAD

**Issue by josh-cook** [cookiej91/challenge-generator#23]
Just add a basic background isaac related to make it look and feel a little more like its binding of isaac related

https://wallpapercave.com/w/wp2264783
https://wallpapercave.com/wp/wp2264785.png
https://wallpapercave.com/w/wp2264789

**Comment by cookiej91** [comment]
http://www.desktop-screens.com/the-binding-of-isaac-wallpapers/3528835.html

**Comment by jackwilsdon** [comment]
Maybe a little higher res than 640x360 @cookiej91 :wink:

**Comment by josh-cook** [comment]
amended 👍  @jackwilsdon

**Comment by jackwilsdon** [comment]
I think this can probably be closed now that #24 is done (and #25 has been opened).
