### ISSUE TITLE
Removal of dark colours

### ISSUE THREAD

**Issue by josh-cook** [cookiej91/challenge-generator#25]
Once #23 has been sorted we should remove the colours that are too dark for the background we have now chosen, and reimplement the old colours that were too light for a white background.

**Comment by jackwilsdon** [comment]
It doesn't look like there are all that many dark colors in the list in the first place;

![colors](https://user-images.githubusercontent.com/1843197/66705355-59ec3e80-ed1d-11e9-9e58-5ef5a23aadc9.png)

It seems like the only ones worth removing are these;

* Black
* Midnight Blue
* Outer Space
